# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "UM Neutrino Research Group"
email: gavin.s.davies@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Neutrino physics research at the University of Mississippi."
baseurl: ""
url: ""
author: "Dr. Gavin S. Davies"
keywords: "neutrino, physics, NOvA, DUNE, EMPHATIC, particle physics"
timezone: "America/Chicago"

include:
  - _pages

sass:
  sass_dir: _sass

# Collections for better content management
collections:
  news:
    output: true
    permalink: /news/:title/
  publications:
    output: true
    permalink: /publications/:title/
  team:
    output: true
    permalink: /team/:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-last-modified-at

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
# Development settings
livereload: true
livereload_port: 35729
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
